### ISSUE TITLE
Question about transcriptome_data.py

### ISSUE THREAD

**Issue by chenyang1999** [owkin/HE2RNA_code#2]
Thanks for your hard work :)
When I try to duplicate your code, I try to execute  python transcriptome_data.py,
i get an error abort:
```
Traceback (most recent call last):
  File "transcriptome_data.py", line 157, in <module>
    main()
  File "transcriptome_data.py", line 147, in main
    df_.columns = [str(f).split('/')[-2]]
  File "/home/hesunan/anaconda3/envs/env/lib/python3.7/site-packages/pandas/core/generic.py", line 4389, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/hesunan/anaconda3/envs/env/lib/python3.7/site-packages/pandas/core/generic.py", line 646, in _set_axis
    self._data.set_axis(axis, labels)
  File "/home/hesunan/anaconda3/envs/env/lib/python3.7/site-packages/pandas/core/internals.py", line 3323, in set_axis
    'values have {new} elements'.format(old=old_len, new=new_len))
ValueError: Length mismatch: Expected axis has 8 elements, new values have 1 elements
```
I try to understand the means of that coda:
```
    for f in tqdm(sorted(path.glob('*/*.txt'))):
        df_ = pd.read_csv(f, sep='\t', header=None, index_col=0)
        print(str(f).split('/'))
        print(df_.columns,str(f).split('/')[-2])
        print(df_.T)
        df_.columns = [str(f).split('/')[-2]]
        df.append(df_.T)
```
Could anyone help me?

**Comment by chenyang1999** [comment]
我找到了解决方案,transcriptome数据中混入了annotations.txt 文件,只要把它去掉即可
```
    for f in tqdm(sorted(path.glob('*/*.txt'))):
        if "annotations.txt" in f:continue
        df_ = pd.read_csv(f, sep='\t', header=None, index_col=0)
        df_.columns = [str(f).split('/')[-2]]
        df.append(df_.T)
```
