### ISSUE TITLE
install openslide-python==1.1.1 error

### ISSUE THREAD

**Issue by PeijinV5** [owkin/HE2RNA_code#9]
Hi,

How are you? I am a PhD student in Bioinformatics and Computation Medicine department at University of Michigan. I am trying to install the "requirements.txt". There was an error when trying to install open slide-python==1.1.1:

File "/tmp/pip-install-686n_fkx/openslide-python_83c86f6362ad4cd58c21cf001e9b9bb2/setup.py", line 2, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools'

I highly appreciate if you could let me know how can I fix it!

Thank you very much,
Peijin

**Comment by chenyang1999** [comment]
# 激活环境

```
conda activate env
```

## 创建指定版本 python 虚拟环境

```
conda create -n env python=3.7.4
conda activate env
# To deactivate an active environment, use
#
#     $ conda deactivate
export CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
python -m pip install --upgrade setuptools
pip install --upgrade pip setuptools==45.2.0
pip install -r requirements.txt

```

 

# 安装llvmlite报错解决：RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for

```
zhang@debian:~$ pip3 install llvmlite==0.16.0
Collecting llvmlite==0.16.0
  Using cached https://files.pythonhosted.org/packages/23/c7/56d7c18564783f33206b3cb6ce861a8d681e8be1a124c5651145ce5aad0f/llvmlite-0.16.0.tar.gz
Building wheels for collected packages: llvmlite
  Running setup.py bdist_wheel for llvmlite ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-s7dyuobp/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpsklqjxv1pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  got version from file /tmp/pip-build-s7dyuobp/llvmlite/llvmlite/_version.py {'version': '0.16.0', 'full': '964cf1d6d725b000c769379a5efe11932fcfc551'}
  running build_ext
  /usr/bin/python3 /tmp/pip-build-s7dyuobp/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-build-s7dyuobp/llvmlite/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.5/subprocess.py", line 383, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
      raise child_exception_type(errno_num, err_msg)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-build-s7dyuobp/llvmlite/ffi/build.py", line 152, in <module>
      main()
    File "/tmp/pip-build-s7dyuobp/llvmlite/ffi/build.py", line 142, in main
      main_posix('linux', '.so')
    File "/tmp/pip-build-s7dyuobp/llvmlite/ffi/build.py", line 108, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/bin/python3' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-s7dyuobp/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-k5q48i8w-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    got version from file /tmp/pip-build-s7dyuobp/llvmlite/llvmlite/_version.py {'version': '0.16.0', 'full': '964cf1d6d725b000c769379a5efe11932fcfc551'}
    running build_ext
    /usr/bin/python3 /tmp/pip-build-s7dyuobp/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-build-s7dyuobp/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.5/subprocess.py", line 383, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-build-s7dyuobp/llvmlite/ffi/build.py", line 152, in <module>
        main()
      File "/tmp/pip-build-s7dyuobp/llvmlite/ffi/build.py", line 142, in main
        main_posix('linux', '.so')
      File "/tmp/pip-build-s7dyuobp/llvmlite/ffi/build.py", line 108, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-s7dyuobp/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-k5q48i8w-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-s7dyuobp/llvmlite/


```

这个报错是因为找不到`llvm-config`这个命令：

```
alias llvm-config="llvm-config-3.9"
export LLVM_CONFIG="/usr/bin/llvm-config-3.9"
```

然后再安装就不会报错了：

```
zhang@debian:~$ pip3 install llvmlite==0.16.0
Collecting llvmlite==0.16.0
  Using cached https://files.pythonhosted.org/packages/23/c7/56d7c18564783f33206b3cb6ce861a8d681e8be1a124c5651145ce5aad0f/llvmlite-0.16.0.tar.gz
Building wheels for collected packages: llvmlite
  Running setup.py bdist_wheel for llvmlite ... done
  Stored in directory: /home/zhang/.cache/pip/wheels/2a/c0/a5/f0d4dc24ba9076d15b0797f84e3fc3e9a6280b56c111f0d6a2
Successfully built llvmlite
Installing collected packages: llvmlite
Successfully installed llvmlite-0.16.0
```
